(dp1
S'output'
p2
S"<type 'exceptions.ValueError'> invalid literal for int() with base 10: ''"
p3
sS'layer'
p4
S'/home/ria/Desktop/web2py/applications/simpleNN/controllers/palomino1.py'
p5
sS'code'
p6
S'<code object <module> at 0x7fa4e43ef1b0, file "/home/ria/Desktop/web2py/applications/simpleNN/controllers/palomino1.py", line 3>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/ria/Desktop/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/ria/Desktop/web2py/applications/simpleNN/controllers/palomino1.py", line 152, in <module>\n  File "/home/ria/Desktop/web2py/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/ria/Desktop/web2py/applications/simpleNN/controllers/palomino1.py", line 109, in result\n    a2=int(request.vars[\'a2\'])\nValueError: invalid literal for int() with base 10: \'\'\n'
p11
s.